version: '3.8'
services:
  backend:
    build: ./app/backend
    ports: ["3000:3000"]
    env_file: .env
    depends_on: [mongo]

  ai-service:
    build: ./app/ai-service
    ports: ["5000:5000"]
    env_file: .env

  mongo:
    image: mongo:7
    ports: ["27018:27017"]
    volumes: [mongo-data:/data/db]

  redis:                          # ← add this entire block
    image: redis:7-alpine
    ports: ["6379:6379"]

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    volumes:
      - redisinsight:/data
volumes:
  mongo-data:
  redisinsight: